spring:
  datasource:
    url: jdbc:postgresql://postgres_server:5432/postgres
    username: postgres
    password: daleb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
      